### PR TITLE
Protect against end after destroy

### PR DESCRIPTION
**Pull request by orgads**

### CODE REVIEW

**Comment by contra** [comment]
@orgads (Not the maintainer) Can you add a test for this? May help speed up merging

**Comment by orgads** [comment]
ping

**Comment by orgads** [comment]
Is this project dead?

**Comment by phated** [comment]
@orgads as with all open source, it'll get merged when it gets merged. People do this in their spare time and likely don't have any right now. Instead of asking if the project is dead, you can phrase things like "anything else I can do to get this over the finish line?" and things like that. Don't chastise maintainers.

**Comment by orgads** [comment]
Sorry, I didn't mean to offend you. I just had bad experience in the past with several orphan projects.

This is a minor fix for a regression in v4, so I expected it would be easy to accept. I saw that it did not get any attention for a while year, so I wondered if the project is still maintained. Could have been more polite, I guess.

**Comment by mafintosh** [comment]
4.1.2

**Comment by orgads** [comment]
Thank you.

**Pull request merged**
