### PR TITLE
fix: Cannot read properties of null (reading length) in stream-shift

### PR DESCRIPTION
**Pull request by PatrickHeneise**
I ran into this issue https://github.com/mafintosh/stream-shift/issues/6 using https://www.npmjs.com/package/@google-cloud/storage. It has been resolved in https://github.com/mafintosh/stream-shift/pull/7, would be great to get this merged. I'll open another PR on `@google-cloud/storage` once there's a new version. Thanks!

### CODE REVIEW

**Comment by mafintosh** [comment]
This is auto picked up by semver but does no harm so will merge

**Comment by PatrickHeneise** [comment]
Would be great if you could release this on npm so I can ask the Google team to upgrade

**Comment by PatrickHeneise** [comment]
Thank you!

**Comment by mafintosh** [comment]
np

**Pull request merged**
