### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by phated**
Replaces #12 

@mafintosh if you are looking for additional maintainer help, feel free to add me to this or any other modules I'm sending stuff to (which means we use them in gulp).

### CODE REVIEW

**Comment by mafintosh** [comment]
3.5.1

**Comment by mafintosh** [comment]
Added you as collab, although this is super stable, but appreciate any help :)
Ping me on any other pending PRs you have for me.

**Comment by phated** [comment]
@mafintosh it doesn't seem like this actually got published.  Can you publish? Thanks 😄

**Comment by mafintosh** [comment]
Oops sorry about that. Fixed :)

**Pull request merged**
