### PR TITLE
use safe-buffer module to make Buffer.from() available in old versions of Node.js

### PR DESCRIPTION
**Pull request by Trott**

### CODE REVIEW

**Comment by Trott** [comment]
(Happy to modify it so it only touches the tests if you'd prefer to not add a module to the actual library code, since there's already code in there to avoid Buffer constructor if `Buffer.from()` exists.)

**Comment by ChALkeR** [comment]
Tracking: https://github.com/nodejs/node/issues/19079

**Comment by ChALkeR** [comment]
@Trott I specifically landed this to https://github.com/mafintosh/duplexify/pull/17 without extra deps.

A one-liner shouldn't require an extra dependency. Perhaps move that to dev deps only, if it's required for tests?

**Comment by Trott** [comment]
@ChALkeR Sure, done.

**Comment by Trott** [comment]
I think since #17 landed, this is obsolete but if I'm mistaken, by all means, re-open.

**Pull request closed without merging**
